### ISSUE TITLE
Support authentication through cfpio auth

### ISSUE THREAD

**Issue by jljouannic** [cfpio/front#11]

**Comment by ghoullier** [comment]
J'ai ajouté un intercepteur HTTP pour gérer la redirection en cas de 401

**Comment by jljouannic** [comment]
J'ai vu. Je suis reparti de ça.

**Comment by jljouannic** [comment]
Fixed in https://github.com/cfpio/front/commit/bffd0dda56678d25a7f9a35b89c74d838fba68c9
