### ISSUE TITLE
Provide basic config to front at runtime

### ISSUE THREAD

**Issue by jljouannic** [cfpio/front#16]
Find a way to provide all base URL to front at runtime before bootstrapping application.

Proposition by @ndeloof :
```javascript
fetch('/api.json', { method: 'HEAD' } )
 .then(response => {
   app.api  = response.headers.get('X-API-Server')
   app.auth = response.headers.get('X-Authentication-Server')
 })
```

Should be easy to set for dev environment with a proxy in browsersync configuration.

**Comment by ndeloof** [comment]
see https://github.com/cfpio/infra/pull/5/files
